// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TooliRent.WebAPI.Migrations
{
    [DbContext(typeof(ToolContext))]
    [Migration("20250905201758_initSeedData")]
    partial class initSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Core.Models.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ToolId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Infrastructure.Models.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("BithDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Infrastructure.Models.ToolCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("ToolCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Electric and battery powered tools for construction and DIY projects",
                            Name = "Power Tools"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Manual tools and basic equipment",
                            Name = "Hand Tools"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Outdoor and gardening equipment for lawn and landscape maintenance",
                            Name = "Garden Tools"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Heavy duty construction and renovation equipment",
                            Name = "Construction Tools"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Professional cleaning tools and pressure washing equipment",
                            Name = "Cleaning Equipment"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Tools", b =>
                {
                    b.Property<int>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToolId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.HasKey("ToolId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            ToolId = 1,
                            CategoryId = 1,
                            Description = "Professional 18V cordless drill with two batteries and charger",
                            Name = "Cordless Drill 18V",
                            Price = 15.99m,
                            QuantityInStock = 3
                        },
                        new
                        {
                            ToolId = 2,
                            CategoryId = 1,
                            Description = "Heavy duty circular saw with carbide blade",
                            Name = "Circular Saw 7.25\"",
                            Price = 22.50m,
                            QuantityInStock = 2
                        },
                        new
                        {
                            ToolId = 3,
                            CategoryId = 1,
                            Description = "Compact angle grinder for cutting and grinding",
                            Name = "Angle Grinder 4.5\"",
                            Price = 18.99m,
                            QuantityInStock = 4
                        },
                        new
                        {
                            ToolId = 4,
                            CategoryId = 1,
                            Description = "Variable speed jigsaw with orbital action",
                            Name = "Jigsaw Variable Speed",
                            Price = 16.75m,
                            QuantityInStock = 0
                        },
                        new
                        {
                            ToolId = 5,
                            CategoryId = 1,
                            Description = "High torque impact driver with quick-change chuck",
                            Name = "Impact Driver",
                            Price = 19.99m,
                            QuantityInStock = 5
                        },
                        new
                        {
                            ToolId = 6,
                            CategoryId = 1,
                            Description = "Random orbital sander with dust collection",
                            Name = "Orbital Sander",
                            Price = 24.99m,
                            QuantityInStock = 2
                        },
                        new
                        {
                            ToolId = 7,
                            CategoryId = 2,
                            Description = "3-piece hammer set: claw, ball peen, and sledge",
                            Name = "Professional Hammer Set",
                            Price = 8.50m,
                            QuantityInStock = 6
                        },
                        new
                        {
                            ToolId = 8,
                            CategoryId = 2,
                            Description = "42-piece metric and imperial socket set with ratchets",
                            Name = "Socket Wrench Set",
                            Price = 12.99m,
                            QuantityInStock = 3
                        },
                        new
                        {
                            ToolId = 9,
                            CategoryId = 2,
                            Description = "20-piece precision screwdriver set with magnetic tips",
                            Name = "Precision Screwdriver Set",
                            Price = 6.75m,
                            QuantityInStock = 8
                        },
                        new
                        {
                            ToolId = 10,
                            CategoryId = 2,
                            Description = "Large tool box with multiple compartments and wheels",
                            Name = "Professional Tool Box",
                            Price = 14.50m,
                            QuantityInStock = 2
                        },
                        new
                        {
                            ToolId = 11,
                            CategoryId = 2,
                            Description = "4-piece adjustable wrench set (6\", 8\", 10\", 12\")",
                            Name = "Adjustable Wrench Set",
                            Price = 9.99m,
                            QuantityInStock = 4
                        },
                        new
                        {
                            ToolId = 12,
                            CategoryId = 3,
                            Description = "21-inch self-propelled gas lawn mower with mulching capability",
                            Name = "Self-Propelled Lawn Mower",
                            Price = 35.99m,
                            QuantityInStock = 2
                        },
                        new
                        {
                            ToolId = 13,
                            CategoryId = 3,
                            Description = "Powerful gas-powered leaf blower with variable speed",
                            Name = "Gas Leaf Blower",
                            Price = 24.99m,
                            QuantityInStock = 3
                        },
                        new
                        {
                            ToolId = 14,
                            CategoryId = 3,
                            Description = "24-inch electric hedge trimmer with rotating handle",
                            Name = "Electric Hedge Trimmer",
                            Price = 21.50m,
                            QuantityInStock = 0
                        },
                        new
                        {
                            ToolId = 15,
                            CategoryId = 3,
                            Description = "Professional 16-inch gas chainsaw with safety features",
                            Name = "Chainsaw 16\"",
                            Price = 42.99m,
                            QuantityInStock = 1
                        },
                        new
                        {
                            ToolId = 16,
                            CategoryId = 3,
                            Description = "Gas-powered string trimmer with dual line head",
                            Name = "String Trimmer",
                            Price = 28.75m,
                            QuantityInStock = 3
                        },
                        new
                        {
                            ToolId = 17,
                            CategoryId = 4,
                            Description = "Professional wet tile saw with diamond blade",
                            Name = "Wet Tile Saw 7\"",
                            Price = 55.99m,
                            QuantityInStock = 1
                        },
                        new
                        {
                            ToolId = 18,
                            CategoryId = 4,
                            Description = "3.5 cubic feet portable concrete mixer",
                            Name = "Portable Concrete Mixer",
                            Price = 68.50m,
                            QuantityInStock = 1
                        },
                        new
                        {
                            ToolId = 19,
                            CategoryId = 4,
                            Description = "35 lb electric demolition hammer with accessories",
                            Name = "Electric Jackhammer",
                            Price = 89.99m,
                            QuantityInStock = 0
                        },
                        new
                        {
                            ToolId = 20,
                            CategoryId = 4,
                            Description = "Professional drum floor sander for hardwood floors",
                            Name = "Floor Sander",
                            Price = 75.25m,
                            QuantityInStock = 1
                        },
                        new
                        {
                            ToolId = 21,
                            CategoryId = 4,
                            Description = "Heavy duty reciprocating saw with multiple blades",
                            Name = "Reciprocating Saw",
                            Price = 32.99m,
                            QuantityInStock = 2
                        },
                        new
                        {
                            ToolId = 22,
                            CategoryId = 5,
                            Description = "3000 PSI electric pressure washer with multiple nozzles",
                            Name = "Electric Pressure Washer",
                            Price = 45.99m,
                            QuantityInStock = 2
                        },
                        new
                        {
                            ToolId = 23,
                            CategoryId = 5,
                            Description = "Hot water extraction carpet cleaning machine",
                            Name = "Professional Carpet Cleaner",
                            Price = 39.99m,
                            QuantityInStock = 1
                        },
                        new
                        {
                            ToolId = 24,
                            CategoryId = 5,
                            Description = "16-gallon wet/dry shop vacuum with multiple attachments",
                            Name = "Shop Vacuum 16 Gallon",
                            Price = 18.75m,
                            QuantityInStock = 4
                        },
                        new
                        {
                            ToolId = 25,
                            CategoryId = 5,
                            Description = "20-inch floor buffer/polisher with pads",
                            Name = "Floor Buffer",
                            Price = 52.50m,
                            QuantityInStock = 1
                        });
                });

            modelBuilder.Entity("Domain.Core.Models.Rental", b =>
                {
                    b.HasOne("Infrastructure.Models.Customers", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.Tools", "Tool")
                        .WithMany("Rentals")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Infrastructure.Models.Tools", b =>
                {
                    b.HasOne("Infrastructure.Models.ToolCategory", "Category")
                        .WithMany("Tools")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Infrastructure.Models.Customers", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Infrastructure.Models.ToolCategory", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("Infrastructure.Models.Tools", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
